Feature
Faisal-Manzer/HASHesApp pull request #3
Opened 2021-05-03 06:46 UTC by arhamathar

get and post request api for blog added

2021-05-03 07:38 UTC, Faisal-Manzer commented
Merge all commits to one... and force push
```git reset --soft HEAD~4
git commit -m "New Commit message```

And in commit message explain what you have done.

2021-05-03 07:49 UTC, Faisal-Manzer requested changes

2021-05-03 07:49 UTC, Faisal-Manzer commented on helpers/constants/app.constants.helper.ts
> +        // permission: PERMISSIONS.VIEW_USERS,
remove comment

2021-05-03 07:49 UTC, Faisal-Manzer commented on helpers/errors/codes.errors.helper.ts
> +export const INVALID_DATA_ERROR = ['INVALID_DATA_ERROR', 422, 'Please enter all fields!'];
Error handling should be more specific. For any form give proper error messages on what field failed what.

2021-05-03 07:49 UTC, Faisal-Manzer commented on models/blog.models.ts
> +        description: {
Rename this field to markdown or html content... whatever you are save saving.

2021-05-03 07:49 UTC, Faisal-Manzer commented on pages/about.tsx
> +/* eslint-disable jsx-quotes */
Remove this. Enable eslint in your editor.

2021-05-03 07:49 UTC, Faisal-Manzer commented on pages/api/blog/index.ts
> +        //     return error(__.NO_PERMISSION);
remove unnecessary comments

2021-05-03 07:49 UTC, Faisal-Manzer commented on pages/api/blog/index.ts
> +    }
for list use helper. don't list like this. it will give all blogs at once.

2021-05-03 07:49 UTC, Faisal-Manzer commented on pages/api/blog/index.ts
> +        let session;
you can use session directly. in user is not authenticated it will give null.

2021-05-03 07:49 UTC, Faisal-Manzer commented on pages/api/blog/index.ts
> +        }
no need for this block

2021-05-03 07:49 UTC, Faisal-Manzer commented on pages/api/blog/index.ts
> +        };
??? what is this?

2021-05-03 07:49 UTC, Faisal-Manzer commented on pages/api/blog/index.ts
> +        });
before saving run proper check on what you are saving... you can use ```yup``` for this.
also give proper error messages for what went wrong.

2021-05-03 07:49 UTC, Faisal-Manzer commented on pages/donate.tsx
> +/* eslint-disable jsx-quotes */
remove this. we are using single quotes every where. use that only.

2021-05-03 07:49 UTC, Faisal-Manzer commented on pages/donate.tsx
> +                        Donate <HeartIcon className="h-6 md:h-12 text-yellow-500" />
why double quotes????

2021-05-03 07:59 UTC, arhamathar commented on pages/api/blog/index.ts
> +        };
It is checking if user has the permission to add blog as not all authenticated user has that permission.

2021-05-03 07:59 UTC, arhamathar commented on pages/api/blog/index.ts
> +        //     return error(__.NO_PERMISSION);
okay it is just for testing purpose

2021-05-03 09:16 UTC, arhamathar commented on pages/api/blog/index.ts
> +        }
so how we will get user related info ??

2021-05-12 06:31 UTC, Faisal-Manzer approved these changes

2021-05-17 12:39 UTC, merged